# Generated by Django 2.1.7 on 2019-05-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_time', models.DateTimeField(verbose_name='leave time')),
                ('from_place', models.CharField(max_length=30)),
                ('to_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TaxiPlaceholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.TaxiGroup')),
            ],
        ),
    ]
