# Generated by Django 2.1.7 on 2019-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxiplaceholder',
            name='id',
        ),
        migrations.AlterField(
            model_name='taxiplaceholder',
            name='vk_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
